name: Build Shamrock APK

on:
  workflow_dispatch:
  push:
    branches: [v1.0.9]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build Shamrock
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"  # 替换废弃的 "adopt"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: gradle-

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease --build-cache --parallel --warning-mode all --stacktrace
          echo "===== 检查APK文件 ====="
          find app/build/outputs/apk -name '*.apk' -exec ls -lh {} \;
          echo "APK_FILES=$(find app/build/outputs/apk -name '*release.apk' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: shamrock-apks
          path: ${{ env.APK_FILES }}
          if-no-files-found: error
